name: Infinite Tracing Test

on: 
  push: 
    branches:
      - main
      - dev
  pull_request:

jobs:
  infinite-tracing:
    needs: build-ruby
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ 2.5.8, 2.6.6, 2.7.1 ]
    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Bundler install
        run: bundle install

      - name: rake test
        run: bundle exec rake test:multiverse[group=infinite_tracing,verbose]
  