name: The Droids You're Looking For

on: push

jobs:
  multiverse_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ "2.1.10" ]
        # ruby-version: [ "2.0.0-p648", "2.1.10", "2.2.10", "2.3.8" ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: ~/.rubies/ruby-${{ matrix.ruby-version }}
          key: v6-ruby-cache-${{ matrix.ruby-version }}
          restore-keys: |
            v6-ruby-cache-${{ matrix.ruby-version }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}
          dependencies: libcurl4-nss-dev build-essential libsasl2-dev libxslt1-dev libxml2-dev

      - run: gem install nokogiri
      - if: ${{ always() }}
        run: cat  /home/runner/.rubies/ruby-2.1.10/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-*/mkmf.log

      # - run: cat /home/runner/.rubies/ruby-${{ matrix.ruby-version }}/lib/ruby/gems/${{ matrix.ruby-version }}/extensions/x86_64-linux/${{ matrix.ruby-version }}/memcached-1.8.0/mkmf.log
      # - if: ${{ always() }}
      #   run: cat /home/runner/.rubies/ruby-${{ matrix.ruby-version }}/lib/ruby/gems/${{ matrix.ruby-version }}/extensions/x86_64-linux/${{ matrix.ruby-version }}/nokogiri-1.9.1/mkmf.log
      # - if: ${{ always() }}
      #   run: cat /home/runner/.rubies/ruby-${{ matrix.ruby-version }}/lib/ruby/gems/${{ matrix.ruby-version }}/extensions/x86_64-linux/${{ matrix.ruby-version }}/nokogiri-1.6.8.1/mkmf.log
