name: The Droids You're Looking For

on: 
  push: 
    branches:
      - main
      - dev
  pull_request:

jobs:
  mini-env:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        # ruby-version: [ "2.0.0-p648", "2.1.10", "2.2.10", "2.3.8", "2.4.10", "2.5.8", "2.6.6", "2.7.1", "jruby-9.2.12.0" ]
        ruby-version: [ "2.2.10" ]
        rails: [ rails31 ]
        # rails: [rails42, rails41, rails40, rails32, rails31, rails30]
        exclude:
          - ruby-version: "2.7.1"
            rails: rails30
          - ruby-version: "2.7.1"
            rails: rails31
          - ruby-version: "2.7.1"
            rails: rails32
          - ruby-version: "2.7.1"
            rails: rails40
          - ruby-version: "2.7.1"
            rails: rails41
          - ruby-version: "2.7.1"
            rails: rails42
          - ruby-version: "2.7.1"
            rails: rails50
          - ruby-version: "2.7.1"
            rails: rails51
          - ruby-version: "2.7.1"
            rails: rails52
          - ruby-version: "2.6.6"
            rails: rails30
          - ruby-version: "2.6.6"
            rails: rails31
          - ruby-version: "2.6.6"
            rails: rails32
          - ruby-version: "2.6.6"
            rails: rails40
          - ruby-version: "2.6.6"
            rails: rails41
          - ruby-version: "2.5.8"
            rails: rails30
          - ruby-version: "2.5.8"
            rails: rails31
          - ruby-version: "2.5.8"
            rails: rails40
          - ruby-version: "2.5.8"
            rails: rails41
          - ruby-version: "2.4.10"
            rails: rails30
          - ruby-version: "2.4.10"
            rails: rails31
          - ruby-version: "2.4.10"
            rails: rails40
          - ruby-version: "2.4.10"
            rails: rails41
          - ruby-version: "2.4.10"
            rails: rails60
          - ruby-version: "2.3.8"
            rails: rails60
          - ruby-version: "2.2.10"
            rails: rails60
          - ruby-version: "2.1.10"
            rails: rails50
          - ruby-version: "2.1.10"
            rails: rails51
          - ruby-version: "2.1.10"
            rails: rails52
          - ruby-version: "2.1.10"
            rails: rails60
          - ruby-version: "2.0.0-p648"
            rails: rails50
          - ruby-version: "2.0.0-p648"
            rails: rails51
          - ruby-version: "2.0.0-p648"
            rails: rails52
          - ruby-version: "2.0.0-p648"
            rails: rails60
          - ruby-version: "jruby-9.2.12.0"
            rails: rails30
          - ruby-version: "jruby-9.2.12.0"
            rails: rails31
          - ruby-version: "jruby-9.2.12.0"
            rails: rails32
          - ruby-version: "jruby-9.2.12.0"
            rails: rails40
          - ruby-version: "jruby-9.2.12.0"
            rails: rails41
          - ruby-version: "jruby-9.2.12.0"
            rails: rails60
          - ruby-version: "jruby-9.2.12.0"
            rails: rails52
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: ~/.rubies/ruby-${{ matrix.ruby-version }}
          key: v5-ruby-cache-${{ matrix.ruby-version }}
          restore-keys: |
            v5-ruby-cache-${{ matrix.ruby-version }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Start mysql
        run: sudo systemctl start mysql

      - name: pkgconfig install
        run: gem install pkg-config -v "~> 1.1.7"

      - name: downgrade openSSL
        run: |
          sudo apt-get remove mysql-client
          wget https://launchpad.net/~ubuntu-security/+archive/ubuntu/ppa/+build/7531893/+files/openssl_1.0.1-4ubuntu5.31_amd64.deb
          sudo dpkg -i openssl_1.0.1-4ubuntu5.31_amd64.deb
          wget https://mirrors.mediatemple.net/debian-security/pool/updates/main/m/mysql-5.5/libmysqlclient18_5.5.62-0%2Bdeb8u1_amd64.deb
          sudo dpkg -i libmysqlclient18_5.5.62-0+deb8u1_amd64.deb
          wget https://mirrors.mediatemple.net/debian-security/pool/updates/main/m/mysql-5.5/libmysqlclient-dev_5.5.62-0%2Bdeb8u1_amd64.deb
          sudo dpkg -i libmysqlclient-dev_5.5.62-0+Bdeb8u1_amd64.deb

      - name: Bundler install
        run: bundle install 

      - name: rake test
        run:  bundle exec rake test:env[${{ matrix.rails }}] TESTOPTS="--verbose"
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_PASSWORD: root

